# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.27
_src_path: https://github.com/OCA/oca-addons-repo-template.git
additional_ruff_rules: []
ci: GitHub
convert_readme_fragments_to_markdown: true
enable_checklog_odoo: true
generate_requirements_txt: true
github_check_license: true
github_ci_extra_env: {}
github_enable_codecov: true
github_enable_makepot: true
github_enable_stale_action: true
github_enforce_dev_status_compatibility: true
include_wkhtmltopdf: false
odoo_test_flavor: Both
odoo_version: 16.0
org_name: Zvonimir Galic
org_slug: zgalic77
rebel_module_groups: []
repo_description: This repository is for test task. It contains Odoo custom module
    for packed picking.
repo_name: Test Task Packed Picking
repo_slug: test_task_packed_picking
repo_website: https://github.com/zgalic77/test_task_packed_picking
use_pyproject_toml: true
use_ruff: true

